version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clinica
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network
